name: Deploy to Github Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use NPM 7
        run: npm i -g npm@latest

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - run: npm ci

      - name: App1
        run: |
          node scripts/app1_getjson.js
        env:
          CSV_URL: ${{ env.CSV_URL }}
          FL_APP_PATH: ${{ env.FL_APP_PATH }}
          FL_PASSWORD: ${{ env.FL_PASSWORD }}
          FL_USERNAME: ${{ env.FL_USERNAME }}
          SS_URL: ${{ env.SS_URL }}
          TABLE_LIST: ${{ env.TABLE_LIST }}
          TABLE_UNZIP: ${{ env.TABLE_UNZIP }}
          TYPE_LIST: ${{ env.TYPE_LIST }}
          TYPE_UNZIP: ${{ env.TYPE_UNZIP }}
          USER_AGENT: ${{ env.USER_AGENT }}
          USER_AGENT1: ${{ env.USER_AGENT1 }}

      - name: App1.1
        run: |
          node scripts/app1b_convert_date.js
        env:
          CSV_URL: ${{ env.CSV_URL }}
          FL_APP_PATH: ${{ env.FL_APP_PATH }}
          FL_PASSWORD: ${{ env.FL_PASSWORD }}
          FL_USERNAME: ${{ env.FL_USERNAME }}
          SS_URL: ${{ env.SS_URL }}
          TABLE_LIST: ${{ env.TABLE_LIST }}
          TABLE_UNZIP: ${{ env.TABLE_UNZIP }}
          TYPE_LIST: ${{ env.TYPE_LIST }}
          TYPE_UNZIP: ${{ env.TYPE_UNZIP }}
          USER_AGENT: ${{ env.USER_AGENT }}
          USER_AGENT1: ${{ env.USER_AGENT1 }}

      - name: App2
        run: |
          node scripts/app2_download_zip.js
        env:
          CSV_URL: ${{ env.CSV_URL }}
          FL_APP_PATH: ${{ env.FL_APP_PATH }}
          FL_PASSWORD: ${{ env.FL_PASSWORD }}
          FL_USERNAME: ${{ env.FL_USERNAME }}
          SS_URL: ${{ env.SS_URL }}
          TABLE_LIST: ${{ env.TABLE_LIST }}
          TABLE_UNZIP: ${{ env.TABLE_UNZIP }}
          TYPE_LIST: ${{ env.TYPE_LIST }}
          TYPE_UNZIP: ${{ env.TYPE_UNZIP }}
          USER_AGENT: ${{ env.USER_AGENT }}
          USER_AGENT1: ${{ env.USER_AGENT1 }}

      - name: App3
        run: |
          node scripts/app3_parse_zip.js
        env:
          CSV_URL: ${{ env.CSV_URL }}
          FL_APP_PATH: ${{ env.FL_APP_PATH }}
          FL_PASSWORD: ${{ env.FL_PASSWORD }}
          FL_USERNAME: ${{ env.FL_USERNAME }}
          SS_URL: ${{ env.SS_URL }}
          TABLE_LIST: ${{ env.TABLE_LIST }}
          TABLE_UNZIP: ${{ env.TABLE_UNZIP }}
          TYPE_LIST: ${{ env.TYPE_LIST }}
          TYPE_UNZIP: ${{ env.TYPE_UNZIP }}
          USER_AGENT: ${{ env.USER_AGENT }}
          USER_AGENT1: ${{ env.USER_AGENT1 }}

      - name: App4
        run: |
          node scripts/app4_unzip.js
        env:
          CSV_URL: ${{ env.CSV_URL }}
          FL_APP_PATH: ${{ env.FL_APP_PATH }}
          FL_PASSWORD: ${{ env.FL_PASSWORD }}
          FL_USERNAME: ${{ env.FL_USERNAME }}
          SS_URL: ${{ env.SS_URL }}
          TABLE_LIST: ${{ env.TABLE_LIST }}
          TABLE_UNZIP: ${{ env.TABLE_UNZIP }}
          TYPE_LIST: ${{ env.TYPE_LIST }}
          TYPE_UNZIP: ${{ env.TYPE_UNZIP }}
          USER_AGENT: ${{ env.USER_AGENT }}
          USER_AGENT1: ${{ env.USER_AGENT1 }}

      - name: App5
        run: |
          node scripts/app5_syncsheet.js
        env:
          CSV_URL: ${{ env.CSV_URL }}
          FL_APP_PATH: ${{ env.FL_APP_PATH }}
          FL_PASSWORD: ${{ env.FL_PASSWORD }}
          FL_USERNAME: ${{ env.FL_USERNAME }}
          SS_URL: ${{ env.SS_URL }}
          TABLE_LIST: ${{ env.TABLE_LIST }}
          TABLE_UNZIP: ${{ env.TABLE_UNZIP }}
          TYPE_LIST: ${{ env.TYPE_LIST }}
          TYPE_UNZIP: ${{ env.TYPE_UNZIP }}
          USER_AGENT: ${{ env.USER_AGENT }}
          USER_AGENT1: ${{ env.USER_AGENT1 }}

      - name: App6
        run: |
          node scripts/app6_tsv.js
        env:
          CSV_URL: ${{ env.CSV_URL }}
          FL_APP_PATH: ${{ env.FL_APP_PATH }}
          FL_PASSWORD: ${{ env.FL_PASSWORD }}
          FL_USERNAME: ${{ env.FL_USERNAME }}
          SS_URL: ${{ env.SS_URL }}
          TABLE_LIST: ${{ env.TABLE_LIST }}
          TABLE_UNZIP: ${{ env.TABLE_UNZIP }}
          TYPE_LIST: ${{ env.TYPE_LIST }}
          TYPE_UNZIP: ${{ env.TYPE_UNZIP }}
          USER_AGENT: ${{ env.USER_AGENT }}
          USER_AGENT1: ${{ env.USER_AGENT1 }}

      - name: Build
        run: |
          npm run build
          npm run export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
